In [1]:
import pandas as pd

In [3]:
detxs= pd.read_csv("demo_AmexTransactions.csv")

In [5]:
detxs.head()

,01/01/2018 Mon,Unnamed: 1,"THORNTONS - PROSPECT, KY",Unnamed: 3,Unnamed: 4,Unnamed: 5,Transportation,Unnamed: 7,7.71,Unnamed: 9,000101530525022270350\n5022280350\nAUTOMATED FUEL\n\n\n\n\n 5022280350 \n AUTOMATED FUEL \n,THORNTONS,13302 W HIGHWAY 42\nPROSPECT\nKY,40059\nUNITED STATES,'320180020387880725',Unnamed: 15
0,01/02/2018 Tue,NaN,"GOOGLE *GOOGLE STORAGE - 855-836-3987, CA",NaN,NaN,NaN,Business Services,NaN,9.99,NaN,A07DGWR0 SELLER\nSELLER\n\n SELLER \n,Google Services,1600 AMPHITHEATRE PKWY\nMOUNTAIN VIEW\nCA,94043-1351\nUNITED STATES,'320180030398782679',NaN
1,01/02/2018 Tue,NaN,"THORNTONS - PROSPECT, KY",NaN,NaN,NaN,Transportation,NaN,11.70,NaN,000201530645027280350\n5022280350\nAUTOMATED F...,THORNTONS,13302 W HIGHWAY 42\nPROSPECT\nKY,40059\nUNITED STATES,'320180030400527501',NaN
2,01/03/2018 Wed,NaN,"AMAZON MKTPLACE PMTS - AMZN.COM/BILL, WA",NaN,NaN,NaN,Merchandise & Supplies,NaN,85.00,NaN,6KWIX54M0UK BOOK STORES\nBOOK STORES\n\n BOOK ...,Amazon Marketplace,410 TERRY AVE N\n-\nSEATTLE\nWA,98109\nUNITED STATES,'320180030401066585',NaN
3,01/03/2018 Wed,NaN,"Amazon Web Services - AWS.Amazon.com, WA",NaN,NaN,NaN,Merchandise & Supplies,NaN,9.46,NaN,BXVJ2YWCER7 WEB SERVICES\nWEB SERVICES\n\n WEB...,AMAZON WEB SERVICES,410 Terry Ave N\nSeattle\nWA,98109\nUNITED STATES,'320180030404248515',NaN
4,01/11/2018 Thu,NaN,"TRADER JOE'S #628 QPS 628 - LOUISVILLE, KY",NaN,NaN,NaN,Merchandise & Supplies,NaN,147.72,NaN,0017185 626-599-3700\n626-599-3700\nGROCERY ST...,Trader Joe's,4600 SHELBYVILLE RD STE 112\nLOUISVILLE\nKY,40207\nUNITED STATES,'320180120538571262',NaN